2025-04-22 10:27:01,188 ERROR: Exception on /api/task_detail/ [GET] [in C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\app\routes\task_detail_routes.py", line 30, in get_all_task_details
    task_details = task_detail.query.all()
                   ^^^^^^^^^^^^^^^^^
AttributeError: module 'app.models.task_detail' has no attribute 'query'
2025-04-22 10:27:35,791 ERROR: Exception on /api/task_detail/ [GET] [in C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\app\routes\task_detail_routes.py", line 30, in get_all_task_details
    task_details = task_detail.query.all()
                   ^^^^^^^^^^^^^^^^^
AttributeError: module 'app.models.task_detail' has no attribute 'query'
2025-04-22 10:28:53,363 ERROR: Exception on /api/task_detail/ [GET] [in C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\app\routes\task_detail_routes.py", line 30, in get_all_task_details
    task_details = task_detail.query.all()
                   ^^^^^^^^^^^^^^^^^
AttributeError: module 'app.models.task_detail' has no attribute 'query'
