2025-04-25 07:52:48,786 ERROR: Exception on /api/user/ [POST] [in D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: create_user() missing 1 required positional argument: 'current_user'
2025-04-25 07:53:01,493 ERROR: Exception on /api/user/ [POST] [in D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: create_user() missing 1 required positional argument: 'current_user'
2025-04-25 07:53:46,976 ERROR: Exception on /api/user/ [POST] [in D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: create_user() missing 1 required positional argument: 'current_user'
2025-04-25 07:55:35,384 ERROR: Exception on /api/user/ [POST] [in D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: create_user() missing 1 required positional argument: 'current_user'
2025-04-25 07:55:49,590 ERROR: Exception on /api/user/ [POST] [in D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: create_user() missing 1 required positional argument: 'current_user'
2025-04-25 08:00:29,283 ERROR: Exception on /api/user/ [POST] [in D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\hoc_python\Flask_Backend_ThucTapSinh\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: create_user() missing 1 required positional argument: 'current_user'
